# Generated by Django 4.0.3 on 2022-03-16 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, max_length=8, null=True)),
                ('edu_level', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
