# Generated by Django 4.0.3 on 2022-03-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_register_student_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register_student',
            table='student',
        ),
    ]
