# Generated by Django 4.0.3 on 2022-03-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_register_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_student',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
